# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51978c836ff2dba777be598e2c3cebddb979be654ae1d3ba938a17df1dfcd3f570495554b8224c0523420e5eafc9420e0f5c3839ffc285d9dddba544a5497eb8

test:
  secret_key_base: 5250fd378805934c0dcc9253b76ceacae2e262856dbef82ce3b76feef637d857d06a0dbff45643034647f892e018c3574609ed2144979e2e7faf1911e9936647

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
